### ISSUE TITLE
Minor mistake in `_posts/2017-10-14-explain-git-in-simple-words.md`

### ISSUE THREAD

**Issue by Pamplemousse** [SMUsamaShah/SMUsamaShah.github.io#1]
First of all: thank you for the very useful and clear blog post.

Spotted a little mistake while reading, in the [Fetch section](https://github.com/SMUsamaShah/SMUsamaShah.github.io/blob/master/_posts/2017-10-14-explain-git-in-simple-words.md#fetch): you wrote "The process of getting updates/changes from remote is called `pull`" where I guess you meant "`fetch`".

Cheers!

**Comment by SMUsamaShah** [comment]
Yes that's definitely a mistake. Thank you for pointing it out. Fixed it.

**Comment by Pamplemousse** [comment]
:+1:
